/* 2020 changes */
/* delete 'dianthus' 'purple' */
/* change 'illumination begonia' variety to 'yellow peach' */
insert into flower
(fname,fvariety,fcontainer)
values
('alyssum','white','flat'),
('alyssum','purple','flat'),
('alyssum','mixed','flat'),
('dahlia','mixed','flat'),
('dianthus','red','flat'),
('dianthus','mixed','flat'),
('dusty miller','silver','flat'),
('gazania','mixed','flat'),
('marigold','yellow','flat'),
('marigold','orange','flat'),
('marigold','bi-color','flat'),
('moss rose','mixed','flat'),
('petunia','midnight blue','flat'),
('petunia','pink','flat'),
('petunia','red','flat'),
('petunia','white','flat'),
('petunia','yellow','flat'),
('petunia','mixed','flat'),
('zinnia','mixed','flat'),
('snap dragon drawf','mixed','flat'),
('snap dragon tall','mixed','flat'),
('verbena','mixed','flat'),
('vinca','red','flat'),
('vinca','white','flat'),
('vinca','lavender','flat'),
('vinca','mixed','flat'),
('salvia','blue','flat'),
('salvia','red','flat'),
('begonia','white','flat'),
('begonia','red','flat'),
('begonia','pink','flat'),
('begonia','mixed','flat'),
('begonia','pink - bronze leaf','flat'),
('begonia','red - bronze leaf','flat'),
('coleus','scarlet','flat'),
('coleus','mixed','flat'),
('impatiens','white','flat'),
('impatiens','red','flat'),
('impatiens','salmon','flat'),
('impatiens','violet','flat'),
('impatiens','hot pink','flat'),
('impatiens','mixed','flat'),
('geranium','red','flower 4.5 inch'),
('geranium','white','flower 4.5 inch'),
('geranium','violet/fuschia','flower 4.5 inch'),
('geranium','pink','flower 4.5 inch'),
('geranium','salmon','flower 4.5 inch'),
('marguerite daisy','yellow','flower 6 inch'),
('wave petunia','midnight blue','hb'),
('wave petunia','sky blue','hb'),
('wave petunia','pink','hb'),
('wave petunia','purple','hb'),
('wave petunia','bordeaux','hb'),
('wave petunia','burgundy star','hb'),
('ivy geranium','red','hb'),
('ivy geranium','pink','hb'),
('ivy geranium','lavender','hb'),
('ivy geranium','salmon','hb'),
('million bells','red','hb'),
('million bells','pink','hb'),
('million bells','blue','hb'),
('million bells','yellow','hb'),
('fuschia','red/white','hb'),
('fuschia','purple/red','hb'),
('rosebud impatiens','sparkler pink','hb'),
('impatiens','red','hb'),
('impatiens','pink','hb'),
('impatiens','mixed','hb'),
('illumination begonia','yellow peach','hb'),
('dragon wing begonia','red','hb'),
('combo hb','blue shades','combo hb'),
('combo hb','pink shades','combo hb'),
('combo hb','magenta yellow blue','combo hb'),
('combo hb','red white blue','combo hb'),
('tomato','better boy','tomato 4 inch'),
('tomato','early girl','tomato 4 inch'),
('tomato','cherry','tomato 4 inch'),
('tomato','roma','tomato 4 inch'),
('tomato','grape','tomato 4 inch'),
('tomato','super steak','tomato 4 inch'),
('tomato','gallon','tomato gallon'),
('fountain grass','purple','grass gallon'),
('herb','basil','herb 4 inch'),
('herb','chives','herb 4 inch'),
('herb','cilantro','herb 4 inch'),
('herb','oregano','herb 4 inch'),
('herb','parsley flat leaf','herb 4 inch'),
('herb','rosemary','herb 4 inch'),
('accent','spikes','accent 4 inch'),
('accent','blackie sweet potato','accent 4 inch'),
('accent','lime sweet potato','accent 4 inch'),
('accent','vinca vine','accent 4 inch'),
('patio pot','pink','patio pot'),
('patio pot','red','patio pot'),
('patio pot','salmon','patio pot'),
('patio pot','violet','patio pot');
